lessons:
  outputs:
    dev:
      dataset: dbt_lokesh
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dbt-ecommerce-15669
      threads: 60
      type: bigquery
  target: dev